openapi: 3.0.3
info:
  title: NLPearl Hotel Availability Mock API
  version: "1.0.0"
servers:
  - url: https://mock.nlpearl.local/api
paths:
  /hotels:
    get:
      summary: List hotels
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Hotel'
  /rooms:
    get:
      summary: List rooms (filter by hotel_id, room_type, bed_type)
      parameters:
        - in: query
          name: hotel_id
          schema: { type: integer }
        - in: query
          name: room_type
          schema: { type: string }
        - in: query
          name: bed_type
          schema: { type: string }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Room'
  /availability:
    get:
      summary: Check availability by date range and filters
      parameters:
        - in: query
          name: check_in_date
          required: true
          schema: { type: string, format: date }
        - in: query
          name: check_out_date
          required: true
          schema: { type: string, format: date }
        - in: query
          name: number_of_adults
          schema: { type: integer, minimum: 1 }
        - in: query
          name: number_of_children
          schema: { type: integer, minimum: 0 }
        - in: query
          name: hotel_id
          schema: { type: integer }
        - in: query
          name: room_type
          schema: { type: string }
        - in: query
          name: bed_type
          schema: { type: string }
        - in: query
          name: min_price
          schema: { type: number }
        - in: query
          name: max_price
          schema: { type: number }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/AvailabilityResult'
                  currency:
                    type: string
                    example: EUR
  /bookings:
    post:
      summary: Create a booking (mock)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [room_id, check_in_date, check_out_date, guest_name]
              properties:
                room_id: { type: integer }
                check_in_date: { type: string, format: date }
                check_out_date: { type: string, format: date }
                guest_name: { type: string }
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
components:
  schemas:
    Hotel:
      type: object
      properties:
        hotel_id: { type: integer }
        hotel_name: { type: string }
        location: { type: string }
        star_rating: { type: integer }
        phone_number: { type: string }
    Room:
      type: object
      properties:
        room_id: { type: integer }
        hotel_id: { type: integer }
        room_type: { type: string }
        bed_type: { type: string }
        capacity_adults: { type: integer }
        capacity_children: { type: integer }
        base_price: { type: number }
    AvailabilityResult:
      type: object
      properties:
        hotel_id: { type: integer }
        room_id: { type: integer }
        date_range:
          type: object
          properties:
            check_in_date: { type: string, format: date }
            check_out_date: { type: string, format: date }
        room_type: { type: string }
        bed_type: { type: string }
        capacity_adults: { type: integer }
        capacity_children: { type: integer }
        nightly_price: { type: number }
        total_price: { type: number }
    Booking:
      type: object
      properties:
        booking_id: { type: integer }
        room_id: { type: integer }
        guest_name: { type: string }
        check_in_date: { type: string, format: date }
        check_out_date: { type: string, format: date }
        total_price: { type: number }
        status: { type: string }